var namespaces_dup =
[
    [ "accent_ns", "d8/d61/namespaceaccent__ns.html", null ],
    [ "all_words_ns", "d4/de6/namespaceall__words__ns.html", null ],
    [ "arith_ns", "d8/d76/namespacearith__ns.html", null ],
    [ "bib_ns", "d8/dda/namespacebib__ns.html", null ],
    [ "buffer_ns", "d4/dbe/namespacebuffer__ns.html", null ],
    [ "classes_ns", "d6/d54/namespaceclasses__ns.html", null ],
    [ "config_ns", "d7/d21/namespaceconfig__ns.html", null ],
    [ "date_ns", "d9/d1f/namespacedate__ns.html", null ],
    [ "err_ns", "df/d1c/namespaceerr__ns.html", null ],
    [ "fp", "d7/df8/namespacefp.html", null ],
    [ "io_ns", "db/d81/namespaceio__ns.html", null ],
    [ "l3_ns", "d7/d27/namespacel3__ns.html", null ],
    [ "main_ns", "d6/d01/namespacemain__ns.html", null ],
    [ "math_ns", "de/d4a/namespacemath__ns.html", null ],
    [ "parser_ns", "d2/dd3/namespaceparser__ns.html", null ],
    [ "post_ns", "d9/dfa/namespacepost__ns.html", null ],
    [ "ra_ns", "da/d92/namespacera__ns.html", null ],
    [ "readline_ns", "da/d3a/namespacereadline__ns.html", null ],
    [ "stack_ns", "db/dfb/namespacestack__ns.html", null ],
    [ "tcommands", "dd/d96/namespacetcommands.html", null ],
    [ "token_ns", "dc/d80/namespacetoken__ns.html", null ],
    [ "tpage_ns", "d2/db0/namespacetpage__ns.html", null ],
    [ "tralics_ns", "db/d93/namespacetralics__ns.html", null ],
    [ "translate_ns", "db/dbc/namespacetranslate__ns.html", null ],
    [ "trees_ns", "d8/dca/namespacetrees__ns.html", null ],
    [ "xkv_ns", "dc/de7/namespacexkv__ns.html", null ]
];